version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "8080:8080"

  jenkins:
    environment:
      JENKINS_URL: http://host.docker.internal:8080
      GITHUB_REPO: https://github.com/Priyank-Vaidya/CloudScale-Assignment

    ports:
      - "8080:8080"